### ISSUE TITLE
Issues 30 april 2015, overkill

### ISSUE THREAD

**Issue by Jelleas** [gverkes/ghost-nas#1]
- `if (players.size() == 2) {...} else { throw new IllegalArgumentException}`. Why do you accept a list of players, if you only accept two players??
    - Even if for the sake of extensibility, most functions in `MultiplayerGame` are build around the game having only two players.
- `SingleplayerGame` seems unfinished (many functions return null). 
    - Points for effort, and nicely done using an abstract `Game` class, yet unnecessary as the specification does not require a singleplayer implementation.
- With your current implementation of `Dictionary` there is no error message of any kind when the dictionary file cannot be found.

**Comment by gverkes** [comment]
fixed all
